version: '3.1'

services: 
  db:
    image: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: password
    ports: 
      - 3306:3306
    expose: 
      - 3306
    volumes: 
      - mydb:/var/lib/mysql

volumes: 
  mydb:
